license_id: cc-by
methodology: Other
methodology_other: More information is available [here](https://data.chc.ucsb.edu/products/CHC_CMIP6/Data_Descriptor_CHC_CMIP6_climate_projection_dataset.pdf)
caveats:
dataset_source: Climate Hazard Center (CHC) (UC Santa Barbara)
package_creator: HDX Data Systems Team
private: False
maintainer: 196196be-6037-4488-8b71-d786adf4c081
owner_org:  6e30eb6d-52f9-49de-b2cd-2d68fced05c5
data_update_frequency: -1
