license_id: cc-by
methodology: Other
caveats:
dataset_source: Climate Hazard Center (CHC) (UC Santa Barbara)
package_creator: HDX Data Systems Team
private: False
maintainer: 196196be-6037-4488-8b71-d786adf4c081
owner_org:  hdx
data_update_frequency: -1
notes:
