# Collector specific configuration
base_url: "reflection.grit.ucsb.edu::CHC_CMIP6/extremes/Tmax"
zip_file: "Daily_Tmax_{product}_{month}.zip"

start_year: 1983
end_year: 2016

scenarios:
  - "2030_SSP245"
  - "2050_SSP245"
  - "2030_SSP585"
  - "2050_SSP585"

products:
  - "cnt_Tmaxgt30C"
  - "cnt_Tmaxgt40p6C"
  - "cnt_Tmaxgt95"
  - "cnt_Tmaxgt99"
  - "monthly_mean"

dataset_description: |
  This climate projection dataset contains global, daily gridded data for the {scenario} scenario to be used in the identification and monitoring of hydroclimatic extremes.

  The Climate Hazards Center Coupled Model Intercomparison Project Phase 6 climate projection dataset (CHC-CMIP6) was developed to support the analysis of climate-related hazards, including extreme heat conditions, over the recent past and in the near-future. Global daily high resolution (0.05°) grids of the Climate Hazards InfraRed Temperature with Stations temperature product form the basis of the 1983–2016 historical record. Large CMIP6 ensembles from the Shared Socioeconomic Pathway 2-4.5 and SSP 5-8.5 scenarios were then used to develop high resolution daily 2030 and 2050 ‘delta’ fields. These deltas were used to perturb the historical observations, thereby generating 0.05° 2030 and 2050 temperature projections. Finally, monthly counts of frequency of extremes for each variable were derived for each time period.

  Two scenarios were used from CMIP6—Shared Socioeconomic Pathway (SSP) 2–4.5 and 5–8.537. The SSP245 scenario is based on ‘middle-of-the-road’ projections of development (SSP2). The SSP585 scenario projects rapid fossil fuel development and increased global market integration (SSP5). These are generally considered the most-likely scenario (SSP245) and the high-emissions scenario (SSP585)

  Given the two projection periods 2025–2035 and 2045–2055, projections for four CMIP6 scenarios (2030_SSP245, 2030_SSP585, 2050_SSP245, 2050_SSP585) were derived. Counts of the number of extreme days per month were calculated for Tmax for the four scenarios. Definitions of extremes for each variable were based on two methods: known thresholds (30°C and 40.6°C) and by calculating pixel-specific breakpoints using the 95th and 99th percentile.

  30°C and 40.6°C represent moderate and extreme heat exposure. These were chosen based on documented thresholds for agricultural and human heat stress. For each variable, year, and scenario, the number of days surpassing each variables’ thresholds were calculated.

  For Tmax for each pixel, the daily 95th and 99th percentiles were calculated using 1983–2016 daily data, resulting in a 95th and 99th percentile value for each variable. For each of these variables, each year (1983–2016), and each of the four scenarios, the number of days for each month were calculated at each pixel that surpass these percentile-defined extreme values.

  More information can be found in this [article in the Nature journal](https://www.nature.com/articles/s41597-024-03074-w) and and in this [technical documentation](https://data.chc.ucsb.edu/products/CHC_CMIP6/Data_Descriptor_CHC_CMIP6_climate_projection_dataset.pdf).
